build: off
version: 1.0.{build}

skip_branch_with_pr: true

init:
- ps: >-

    git config --global core.sharedRepository true

    git config --global core.longpaths true

    git config --global core.autocrlf input

    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
            https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
            Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
              Write-Host "There are newer queued builds for this pull request, skipping build."
              Exit-AppveyorBuild
            }

    If (($env:SKIP_NOTAG -eq "true") -and ($env:APPVEYOR_REPO_TAG -ne "true")) {
              Write-Host "Skipping build, not at a tag."
              Exit-AppveyorBuild
          }

environment:

  PYPI_VENDOR_DIR: .\tests\pypi\
  PYTHONIOENCODING: utf-8
  GIT_ASK_YESNO: false
  SHELL: windows
  PYTHON_ARCH: 64
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_SKIP_FINALIZE_ON_EXIT: true
  PYTHON: C:\Python36-x64
  PYTHON_VERSION: 3.6.x

  matrix:

    - TEST_SUITE: not install
    - TEST_SUITE: install

install:
- python -m pip install --upgrade pip
- python -m pip install --upgrade detox

cache:
- '%LocalAppData%\pip\cache'
- '%LocalAppData%\pipenv\cache'

test_script:

- detox
